training_setup:
  selected_features:
  - OFF_HOME_FTHG_R3
  - OFF_HOME_FTHG_R5
  - DEF_HOME_FTAG_R3
  - DEF_HOME_FTAG_R5
  - OFF_HOME_HS_R3
  - OFF_HOME_HS_R5
  - DEF_HOME_AS_R3
  - DEF_HOME_AS_R5
  - OFF_HOME_HST_R3
  - OFF_HOME_HST_R5
  - DEF_HOME_AST_R3
  - DEF_HOME_AST_R5
  - OFF_HOME_HC_R3
  - OFF_HOME_HC_R5
  - DEF_HOME_AC_R3
  - DEF_HOME_AC_R5
  - DIS_HOME_HY_R3
  - DIS_HOME_HY_R5
  - DIS_HOME_AY_R3
  - DIS_HOME_AY_R5
  - DIS_HOME_HR_R3
  - DIS_HOME_HR_R5
  - DIS_HOME_AR_R3
  - DIS_HOME_AR_R5
  - OFF_HOME_SHOT_ACCURACY_R3
  - OFF_HOME_SHOT_ACCURACY_R5
  - DIS_HOME_DISCIPLINE_SCORE_R3
  - DIS_HOME_DISCIPLINE_SCORE_R5
  - OFF_AWAY_FTAG_R3
  - OFF_AWAY_FTAG_R5
  - DEF_AWAY_FTHG_R3
  - DEF_AWAY_FTHG_R5
  - OFF_AWAY_AS_R3
  - OFF_AWAY_AS_R5
  - DEF_AWAY_HS_R3
  - DEF_AWAY_HS_R5
  - OFF_AWAY_AST_R3
  - OFF_AWAY_AST_R5
  - DEF_AWAY_HST_R3
  - DEF_AWAY_HST_R5
  - OFF_AWAY_AC_R3
  - OFF_AWAY_AC_R5
  - DEF_AWAY_HC_R3
  - DEF_AWAY_HC_R5
  - DIS_AWAY_AY_R3
  - DIS_AWAY_AY_R5
  - DIS_AWAY_HY_R3
  - DIS_AWAY_HY_R5
  - DIS_AWAY_AR_R3
  - DIS_AWAY_AR_R5
  - DIS_AWAY_HR_R3
  - DIS_AWAY_HR_R5
  - OFF_AWAY_SHOT_ACCURACY_R3
  - OFF_AWAY_SHOT_ACCURACY_R5
  - DIS_AWAY_DISCIPLINE_SCORE_R3
  - DIS_AWAY_DISCIPLINE_SCORE_R5
  - CTX_HOME_REST_DAYS
  - CTX_AWAY_REST_DAYS
  - MKT_IMPLIED_HOME
  - MKT_IMPLIED_DRAW
  - MKT_IMPLIED_AWAY
